services:
  open-webui:
    ports:
      - 8080:8080
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:ollama
    environment:
      - WEBUI_AUTH=False
      - ENV=dev

volumes:
  ollama:
    external: true
    name: ollama
  open-webui:
    external: true
    name: open-webui
